version: "3"

services:
  scaleeweb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    command: npm run dev